remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
# title: B.Safarli
description: Let me inform you that, main purpose of this site is testing/practicing only. You shouldn't use it for your production works
show_downloads: true


theme: jekyll-theme-tactile